In [1]:
d = {'key1': 'item', 'key2' :'item2'}
d

{'key1': 'item', 'key2': 'item2'}

In [3]:
d['key1'] = 'changed'
d['key2'] = 'new'

In [4]:
d

{'key1': 'changed', 'key2': 'new'}

In [6]:
f  =(1,2,3,4,5)
f = {1,2,3,4,5,6,1,3,4,5,6,1,2,3,}
print(f)

{1, 2, 3, 4, 5, 6}


In [8]:
True

True

In [25]:
if "ankita" == "ankita":
    print("ankita")
elif 'akanksha' == 'akanksha':
    print("akanksha")
else:
    print("not ankita")
    
    

ankita


In [22]:
seq = [1,2,3,4,5]
for a in  seq:
    print(a)
    

1
2
3
4
5


In [23]:
for a in range(1,6):
    print("*")

*
*
*
*
*


In [36]:
for a in range (3): 
    for i in range(5,7):
        print("&" ,end=" ")
    print()    

& & 
& & 
& & 


In [32]:
string = input("enter a string :" );
lenght =len(string)
i=0
for a in range (-1, (-lenght-1), -1):
    print(string[i] ,"\t" , string[a])
    i+=1

enter a string :akansha
a 	 a
k 	 h
a 	 s
n 	 n
s 	 a
h 	 k
a 	 a


# #while loop

In [37]:
i = 0;
while i<12:
    print(f' i is {i}')
    i = i+1

 i is 0
 i is 1
 i is 2
 i is 3
 i is 4
 i is 5
 i is 6
 i is 7
 i is 8
 i is 9
 i is 10
 i is 11


In [38]:
list(range(5))

[0, 1, 2, 3, 4]

In [45]:
x = [1,2,3,4]


In [46]:
out = []
for item in x:
    out. append(item**2)
print(out)    

[1, 4, 9, 16]


In [47]:
[item**2 for item in x]

[1, 4, 9, 16]

In [48]:
def my_func(param='default'):
    """
    docstring goes here.
    """
    print(param)

In [49]:
my_func

<function __main__.my_func(param='default')>

In [50]:
my_func()

default


In [51]:
my_func("new para")

new para


In [52]:
my_func(param = "new para")

new para


In [53]:
def square(x):
    return x**2

In [54]:
out  = square(2)

In [55]:
print(out)

4


In [56]:
square(4)


16

In [57]:
def cube(x):
    return x**3
out = cube(5)
print(out)

125


In [58]:
cube(9)

729

In [59]:
def times2(var):
    return var*2
times2(10)

20

In [60]:
lambda var: var*2

<function __main__.<lambda>(var)>

In [69]:
add = lambda x : x +1

In [70]:
result = add(3)

In [71]:
result

4

In [73]:
lambda x:x*2

<function __main__.<lambda>(x)>

In [74]:
add = lambda x : x*2


In [75]:
add(3)

6

In [76]:
t = lambda x: x*x

In [77]:
t(9)

81

In [78]:
seq = [1,2,3,4,5]

In [83]:
a = list(filter(lambda x:x % 2==0,seq))

In [84]:
print(a)

[2, 4]


In [88]:
b = list(map(lambda x : x*x ,a))

In [89]:
print(b)

[4, 16]


In [95]:
from functools import reduce
c = reduce(lambda a,b : a+b,b)

In [96]:
print(c)

20


In [98]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  

In [99]:
%pwd

'C:\\Users\\akanksha'

In [100]:
%ls 

 Volume in drive C is Windows-SSD
 Volume Serial Number is E415-ECED

 Directory of C:\Users\akanksha

01-02-2024  23:12    <DIR>          .
26-02-2023  14:45    <DIR>          ..
25-01-2024  14:04    <DIR>          .anaconda
18-01-2024  14:35    <DIR>          .cache
01-02-2024  23:12    <DIR>          .conda
25-01-2024  14:05                25 .condarc
25-01-2024  14:04    <DIR>          .continuum
01-02-2024  16:20    <DIR>          .ipynb_checkpoints
25-01-2024  15:08    <DIR>          .ipython
25-01-2024  14:23    <DIR>          .jupyter
06-09-2023  18:52    <DIR>          .vscode
06-10-2023  18:02                20 a=10;.pl
24-12-2023  16:39               245 add.c
25-01-2024  14:11    <DIR>          anaconda3
26-02-2023  14:28    <DIR>          Contacts
27-01-2024  22:15    <DIR>          Desktop
26-01-2024  15:57    <DIR>          Documents
27-01-2024  19:00    <DIR>          Downloads
26-02-2023  14:28    <DIR>          Favorites
08-10-2023  12:05                21 hello world

In [102]:
%%HTML
<body> Hi </body>

this gives us the average time it takes to run the particular
command

In [105]:
%%timeit
square_evens = [n*n for n in range(0,1000)]

34.6 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [106]:
import numpy as np

In [107]:
myList = [1,2,3,4]

In [108]:
myList

[1, 2, 3, 4]

In [123]:
np.array(myList)

array([1, 2, 3, 4])

In [122]:
myList

[1, 2, 3, 4]

In [112]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [113]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.zeros(3)

array([0., 0., 0.])

In [118]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.ones(4)


array([1., 1., 1., 1.])

In [121]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace(like range )
return evenly spaced numbers over a specified interval 
the spaces are linear

In [124]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [125]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye 
creates an identity matrix

In [127]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random(rand,randn
Numpy also has a lot of ways to create random number array

In [129]:
np.random.rand(2)

array([0.37852881, 0.43715659])

In [130]:
np.random.rand(5,5)

array([[0.66306208, 0.88620332, 0.50488092, 0.37234046, 0.56023593],
       [0.57615887, 0.21194047, 0.39596155, 0.74998242, 0.30906905],
       [0.25475939, 0.01572885, 0.77092745, 0.00316656, 0.1477218 ],
       [0.73400759, 0.16146795, 0.29520939, 0.44240708, 0.89927678],
       [0.23508097, 0.14383581, 0.61887559, 0.74529506, 0.64579427]])

In [131]:
np.random.randn(5,5)

array([[-0.13153935,  1.00388738,  1.78812898,  0.19707766,  0.43417677],
       [-0.43315151, -0.6741375 ,  0.03952652, -1.31403481,  0.2425192 ],
       [ 1.04818345, -2.60382703,  1.13592486, -0.14360518,  1.00071142],
       [-0.91741259,  1.12762787,  0.03204941, -0.65096685,  0.03146971],
       [-1.52071385, -0.80170132, -0.26737147, -0.99001059, -0.66347788]])

In [132]:
np.random.randint(1,100)

50

In [133]:
arr = np.arange(25)

In [136]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [135]:
ranarr = np.random.randint(0,50,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [137]:
ranarr

array([10, 20, 23,  6, 36,  4,  1, 48, 16, 32])

In [149]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [142]:
ranarr.max()

48

In [143]:
ranarr.argmax()

7

In [144]:
ranarr.min()

1

In [146]:
ranarr.argmin()

6

In [147]:
arr.shape

(25,)

arr.reshape(1,25).shape 

In [150]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
arr.reshape(5,5).shape

(5, 5)

dtype
you can also grab the data type of the object in the array

In [152]:
arr.data   #gives the data location

In [153]:
arr.dtype  ##gives the data type *************

dtype('int32')

In [160]:
list2 = ['a','b','c']

In [161]:
arr3 = np.array(list2)

In [162]:
arr3.dtype

dtype('<U1')

Numpy indexing and selection

In [164]:
#creating sample array
arr4 = np.arange(0,11)

In [165]:
arr4.dtype

dtype('int32')

In [166]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

bracket indexing and selection
the simplest way to pick one or some elements of an array
looks  very similar to python list:

In [167]:
arr4[8]

8

In [168]:
arr4[1:5]

array([1, 2, 3, 4])

In [169]:
arr4[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
arr4[:7]

array([0, 1, 2, 3, 4, 5, 6])

Broadcasting
numpy array differ from a normal python list because of their ability
to broadcast

In [172]:
arr4[0:5] = 100
arr4

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [173]:
slice_of_arr = arr4[0:6]

In [174]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [175]:
slice_of_arr[:] =  99 

In [176]:
slice_of_arr 

array([99, 99, 99, 99, 99, 99])

In [177]:
arr4     #the changes also occur in the original array , no copies of array are made

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [178]:
# to get a copy , need to be explicit
arr_copy = arr4.copy()

In [179]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2D array (matrices)

the  general format is arr_2d[row][col] or arr_2d
[row,col]. i recommend usually using the comma notation
for clarity.

In [5]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

NameError: name 'np' is not defined

In [6]:
arr_2d

NameError: name 'arr_2d' is not defined

In [184]:
arr_2d[0]

array([ 5, 10, 15])

In [185]:
arr_2d[1]

array([20, 25, 30])

In [186]:
arr_2d[1][0]

20

In [3]:
arr_2d[1,0]  #this is same as above

NameError: name 'arr_2d' is not defined

2D array slicing

In [2]:
arr_2d

NameError: name 'arr_2d' is not defined

In [1]:
arr_2d[:2,1:]

NameError: name 'arr_2d' is not defined