In [2]:
import numpy as np

In [3]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr_2d[0]

array([ 5, 10, 15])

In [6]:
arr_2d[1]

array([20, 25, 30])

In [7]:
arr_2d[1][0]

20

In [8]:
arr_2d[1,0]

20

In [10]:
arr_2d[:2,1:]     #all rows beore 2 ,and all column after 1 and also 1

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [12]:
arr_2d[2]

array([35, 40, 45])

In [13]:
arr_2d[:,1]

array([10, 25, 40])

In [14]:
arr_2d[2:]

array([[35, 40, 45]])

In [15]:
arr_2d[:,1]

array([10, 25, 40])

FANCY INDEXING
fancy indexing allow you to select entire row or column
out of order ,to show this ,let's quickly build out a numpy array

In [17]:
arr2d = np.zeros((10,10))

In [18]:
arr2d.shape

(10, 10)

In [25]:
arr_lenght = arr2d.shape[1]

In [29]:
arr_lenght

10

In [26]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [27]:
for i in range(arr_lenght):
    arr2d[i] = i

In [28]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [31]:
arr2d[[2,4,6,8,9]]  #this is a fancy indexing

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [32]:
arr2d[[6,5,2,0]]  #order does not matter

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

SELECTION
use of brackets for selection based of comparison operator

In [35]:
arr5 = np.arange(1,11)

In [36]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr5 > 5 #gives a boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr5 > 7

In [40]:
 bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [42]:
arr5[bool_arr]

array([ 8,  9, 10])

In [43]:
arr5[arr5>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x = 8
arr5[arr5>x]

array([ 9, 10])

In [45]:
arr6 = np.arange(0,20)

In [46]:
arr6 + arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [47]:
arr7 = np.arange(120,140)

In [48]:
arr6 + arr7

array([120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144,
       146, 148, 150, 152, 154, 156, 158])

In [50]:
arr6 -arr7

array([-120, -120, -120, -120, -120, -120, -120, -120, -120, -120, -120,
       -120, -120, -120, -120, -120, -120, -120, -120, -120])

In [51]:
arr6/arr6

C:\Users\akanksha\AppData\Local\Temp\ipykernel_23764\61916801.py:1: RuntimeWarning: invalid value encountered in divide
  arr6/arr6


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
1/arr6

C:\Users\akanksha\AppData\Local\Temp\ipykernel_23764\3180675830.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr6


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [53]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [54]:
np.exp(arr6)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])